name: front_end
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0-282.2.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.6
  http: ^1.2.2
  camera: ^0.10.0
  
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: assets/app_icon.png


flutter:
  uses-material-design: true

  assets:
    - assets/background_image.jpg
    - assets/bg-1.png
    - assets/bg-2.jpg
    - assets/background.png
    - assets/app_icon.png


  
  fonts:
    - family: ClickerScript
      fonts:
        - asset: assets/fonts/ClickerScript-Regular.ttf
